#!/usr/bin/env bash
# debugging nginx port 80
# My Soultion: Delete the existing ../sites-enabled/default and replace with a copy of
# ../sites-available/default. It can be done by creating a symbolic link.
sude ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx resrart
